### ISSUE TITLE
[Feat] Swift Data 사용을 위한 준비

### ISSUE THREAD

**Issue by Naknakk** [DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous#29]
## 🚩 TO-DO
- [ ] SwiftData에 대해 공부하고, 추상화 된 채로 사용할 수 있도록 정리합니다.

**Comment by Naknakk** [comment]
알아본 결과 SwiftData를 뷰 외부에서 사용하도록 하기에는 폼이 너무 많이 들고, 엄청 효율적인지..도 잘 모르겠더라구요. 그냥 공식 문서 그대로 뷰에서 저장하고 쿼리해서 가져오는 방식이 지금 생각하기엔 가장 적합한 것 같습니다.

**Comment by WooFeather** [comment]
좋습니다! 공부하시느라 고생 많으셨어요!!👍
